name = "dingding"
main = "./src/index.js"
compatibility_date = "2022-11-08"

[[kv_namespaces]]
binding = "LINK"
id = "a8ae47712cb64593812b5ac860f0088c"
preview_id = "a8ae47712cb64593812b5ac860f0088c"

[site]
bucket = "./static/dist"
